#!/usr/bin/env python3
"""Batch 3 — incantesimi livello 4, 5 e 6 (aggiunte)."""
import os, re, sys

path = os.path.join(os.path.dirname(__file__), '../js/data/spells-list.js')
content = open(path).read()
assert content.rstrip().endswith('];')
content = content.rstrip()[:-2].rstrip()

new_block = """
  // ── Livello 4 — aggiunte ─────────────────────────────────────────────
  { name:'Tentacoli Neri',           level:{mago:4,stregone:4,arcanista:4}, school:'Congiunzione', subschool:'Creazione', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Media', target:'Area in raggio 6 m', duration:'1 round/livello (dis.)', savingThrow:'Vedi testo', spellResistance:'no', description:'Tentacoli neri riempiono l\'area: attaccano (+10 TxC, stritolamento 1d6+4 danni) ogni creatura nell\'area.' },
  { name:'Ammaliare i Mostri',       level:{mago:4,stregone:4,arcanista:4,bardo:3}, school:'Ammaliamento', subschool:'Fascino', descriptor:'Mente', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 mostro', duration:'1 giorno/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Come Magia degli Incantami ma funziona su qualsiasi tipo di creatura (non solo umanoidi).' },
  { name:'Confusione',               level:{mago:4,stregone:4,arcanista:4,bardo:3}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Media', target:'Tutte le creature in raggio 4,5 m', duration:'1 round/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'I bersagli agiscono in modo caotico: attaccano alleati, fuggono, balbettano o agiscono normalmente (d%/round).' },
  { name:'Porta Dimensionale',       level:{mago:4,stregone:4,arcanista:4,bardo:4}, school:'Congiunzione', subschool:'Teletrasporto', descriptor:'', components:'V', castingTime:'1 azione standard', range:'Lunga (120 m + 12 m/livello)', target:'Tu e oggetti (max 100 kg/livello) o una creatura', duration:'Istantanea', savingThrow:'Nessuno e Volontà annulla (innocuo)', spellResistance:'si', description:'Teletrasporta te stesso (e chi tocchi) in un posto che vedi o conosci entro il raggio.' },
  { name:'Tempesta di Ghiaccio',     level:{mago:4,stregone:4,arcanista:4,druido:4}, school:'Evocazione', subschool:'', descriptor:'Freddo', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Lunga', target:'Pioggia di ghiaccio in raggio 6 m', duration:'1 round', savingThrow:'Nessuno', spellResistance:'si', description:'3d6 fred + 2d6 forza a tutte le creature nell\'area; terreno difficile per 1 round/livello dopo.' },
  { name:'Invisibilità Superiore',   level:{mago:4,stregone:4,arcanista:4,bardo:4}, school:'Illusione', subschool:'Oscuramento', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Personale o tocco', target:'Incantatore o creatura toccata', duration:'1 minuto/livello (dis.)', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Come Invisibilità ma rimane invisibile anche attaccando o lanciando incantesimi.' },
  { name:'Uccisore Fantasmatico',    level:{mago:4,stregone:4,arcanista:4}, school:'Illusione', subschool:'Fantasia', descriptor:'(Mente, Paura)', components:'V, S', castingTime:'1 azione standard', range:'Media', target:'1 creatura vivente', duration:'Istantanea', savingThrow:'Volontà dis (vedi testo); poi TS Fortitudine', spellResistance:'si', description:'Crea l\'immagine del peggior terrore del bersaglio: se fallisce Volontà subisce 3d6 danni INT; poi Fortitudine o mori di paura.' },
  { name:'Pelle di Pietra',         level:{mago:4,stregone:4,arcanista:4,druido:5}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'DR 10/adamantio per la durata (o finché assorbe 10 danni/livello, max 150).' },
  { name:'Muro di Fuoco',            level:{mago:4,stregone:4,arcanista:4,druido:5}, school:'Evocazione', subschool:'', descriptor:'Fuoco', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Media', target:'Muro di fuoco rettilineo o circolare', duration:'Concentrazione + 1 round/livello', savingThrow:'Riflessi dimezza', spellResistance:'si', description:'Muro di fuoco: 2d4 danni fuoco a chi si avvicina (entro 3 m); 2d6+1/livello (max +20) a chi attraversa.' },
  { name:'Muro di Ghiaccio',         level:{mago:4,stregone:4,arcanista:4}, school:'Evocazione', subschool:'', descriptor:'Freddo', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Media', target:'Muro di ghiaccio rettilineo o semicupolato', duration:'1 minuto/livello', savingThrow:'Riflessi (vedi testo)', spellResistance:'si', description:'Muro di ghiaccio 2,5 cm/4 livelli spessore; chi lo attraversa 2d6 freddo; si frantuma in schegge (1d6 buchi, 50% tutto).' },
  { name:'Grido',                    level:{mago:4,stregone:4,arcanista:4,bardo:4}, school:'Evocazione', subschool:'', descriptor:'Sonoro, Linguaggio', components:'V', castingTime:'1 azione standard', range:'Cono 9 m', target:'Creature nel cono', duration:'Istantanea', savingThrow:'Fortitudine parziale', spellResistance:'si', description:'5d6 danni sonori; acceca 2d6 round e assorda permanentemente (TS Fortitudine dimezza danni e annulla accecamento/sordità).' },
  { name:'Libertà di Movimento',     level:{chierico:4,druido:4,bardo:4,ranger:4,paladino:4,inquisitore:4}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, M, DF', castingTime:'1 azione standard', range:'Personale o tocco', target:'Incantatore o creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Si muove normalmente ignorando magie di immobilizzazione, sott\'acqua nuota senza penalità; non può essere raggruppato da CMB.' },
  { name:'Potere Divino',            level:{chierico:4,inquisitore:4}, school:'Evocazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1 round/livello', savingThrow:'Nessuno', spellResistance:'no', description:'+6 FOR, +6 COS, +1 attacco da BAB bonus; tiro per colpire e doppio danni come bastonata sacra.' },
  { name:'Restaurazione',            level:{chierico:4,paladino:4}, school:'Congiunzione', subschool:'Guarigione', descriptor:'', components:'V, S, M', castingTime:'1 minuto', range:'Tocco', target:'Creatura toccata', duration:'Istantanea', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Rimuove livelli negativi, ripristina 1d4 punti characteristic ridotti, 1 punto maledizione, possessione, ecc.' },
  { name:'Protezione dalla Morte',   level:{chierico:4,paladino:4,druido:5,ranger:4}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Immunità ai livelli negativi, alle energie negative e a effetti che uccidono istantaneamente.' },
  { name:'Neutralizzare il Veleno',  level:{chierico:4,druido:3,paladino:4,ranger:3,alchimista:4,bardo:4,inquisitore:4}, school:'Congiunzione', subschool:'Guarigione', descriptor:'', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata o 1 kg di sostanza', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo, oggetto)', spellResistance:'si', description:'Neutralizza veleni nell\'area bersaglio; detossica un veleno attivo senza cura danni già inferti.' },
  { name:'Scrying',                  level:{chierico:4,druido:4,mago:4,stregone:4,arcanista:4,bardo:3}, school:'Divinazione', subschool:'Sfera Cristallina', descriptor:'', components:'V, S, M/DF/F', castingTime:'1 ora', range:'Vedi testo', target:'1 creatura', duration:'1 minuto/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Osserva a distanza la creatura bersaglio tramite un sensore magico invisibile.' },
  { name:'Ancora Dimensionale',      level:{chierico:4,mago:4,stregone:4,arcanista:4}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Media', target:'1 creatura', duration:'1 minuto/livello', savingThrow:'Nessuno', spellResistance:'si', description:'Impedisce teletrasporti, viaggi planari e qualsiasi movimento extradimensionale alla creatura bersaglio.' },
  { name:'Espulsione',               level:{chierico:4,mago:4,stregone:4,arcanista:4,inquisitore:4}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura extradimensionale', duration:'Istantanea', savingThrow:'Volontà annulla', spellResistance:'si', description:'Espelle istantaneamente una creatura extradimensionale nel suo piano di origine.' },

  // ── Livello 5 — aggiunte ─────────────────────────────────────────────
  { name:'Nuvola Velenosissima',      level:{mago:5,stregone:5,arcanista:5}, school:'Congiunzione', subschool:'Creazione', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Media', target:'Nuvola 6 m raggio', duration:'1 min/livello', savingThrow:'Fortitudine parziale', spellResistance:'no', description:'Gas verde: 1d4 COS/round (Fortitudine dimezza a 1). Le creature con 3 o meno PF morono. Si disperde in vento moderato.' },
  { name:'Polimorfismo Malevolo',     level:{druido:5,mago:5,stregone:5,arcanista:5}, school:'Trasmutazione', subschool:'Polimorfismo', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Corta', target:'1 creatura', duration:'Permanente', savingThrow:'Fortitudine annulla', spellResistance:'si', description:'Trasforma una creatura in un animale Piccolo o più piccolo (perde tutte le sue abilità speciali; stat animale per base).' },
  { name:'Bloccare i Mostri',         level:{mago:5,stregone:5,arcanista:5,bardo:4,inquisitore:5}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S, F/DF', castingTime:'1 azione standard', range:'Media', target:'1 o più creature viventi, max 1/livello', duration:'1 round/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Come Bloccare le Persone ma funziona su qualsiasi tipo di creatura.' },
  { name:'Dominare le Persone',       level:{mago:5,stregone:5,arcanista:5,bardo:4}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 round', range:'Corta', target:'1 umanoide', duration:'1 giorno/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Controlla telepaticamente un umanoide: può impartirgli ordini con azione standard; richiede TS ogni nuovo ordine contrario alla natura.' },
  { name:'Imbecillire',               level:{mago:5,stregone:5,arcanista:5}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura', duration:'Istantanea', savingThrow:'Volontà annulla', spellResistance:'si', description:'Abbassa INT e CAR a 1; la creatura non può lanciare incantesimi né usare buff INT/CAR. Cura solo Restaurazione.' },
  { name:'Telecinesi',                level:{mago:5,stregone:5,arcanista:5}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Lunga (120 m + 12 m/livello)', target:'Oggetto(i) o creature', duration:'Concentrazione (max 1 round/livello)', savingThrow:'Volontà annulla (oggetto)', spellResistance:'si', description:'Muovi oggetti (max 250 kg/livello) a 9 m/round; o lancia un\'arma: attacco come BAB+MOD INT, 1d6/100 kg; o afferra creatura (CMB=CL).' },
  { name:'Passaggio nei Muri',        level:{mago:5,stregone:5,arcanista:5}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, F', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 ora/livello (dis.)', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Il soggetto può passare attraverso muri in pietra o legno spessi max 1,8 m+0,3 m/3 livelli (lentissimo: 3 m/round).' },
  { name:'Spezzare l\'Incantesimo',  level:{chierico:5,paladino:4,mago:5,stregone:5,arcanista:5,bardo:4,inquisitore:5}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 minuto', range:'Corta', target:'Max 1 creatura/4 livelli in raggio 9 m', duration:'Istantanea', savingThrow:'Vedi testo', spellResistance:'no', description:'Rimuove effetti di incantamento, maledizioni, imprecazioni e simili su max 1 creatura/4 livelli.' },
  { name:'Volo Posato',               level:{mago:5,stregone:5,arcanista:5}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, F', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 minuto/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Velocità di volo 27 m (manovrabilità perfetta).' },
  { name:'Resurrezione dei Morti Autentica', level:{chierico:7,druido:7,oracolo:7,sciamano:7}, school:'Congiunzione', subschool:'Guarigione', descriptor:'', components:'V, S, M, DF', castingTime:'10 minuti', range:'Tocco', target:'Creatura morta toccata', duration:'Istantanea', savingThrow:'Nessuno, Volontà annulla (vedi testo)', spellResistance:'si', description:'Come Resurrezione dei Morti ma non richiede il corpo originale (basta un capello); riporta anche se morto da anni (1/livello).' },
  { name:'Simbolo del Dolore',        level:{chierico:5,mago:5,stregone:5,arcanista:5}, school:'Necromanza', subschool:'', descriptor:'Male', components:'V, S, M', castingTime:'10 minuti', range:'0 m', target:'Segno creato', duration:'Vedi testo', savingThrow:'Fortitudine annulla', spellResistance:'si', description:'Glifo che causa dolore acuto (-4 a TxC, tiri abilità e prove) a chi fallisce il TS per 1 ora/livello.' },
  { name:'Forma Gasosa',             level:{mago:3,stregone:3,arcanista:3,alchimista:3}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Personale o tocco', target:'Incantatore o creatura toccata', duration:'2 minuti/livello (dis.)', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Il soggetto diventa nebbia: DR 10/magia, immunità a veleni/critici/frecce; velocità volo 3 m (manovrabilità perfetta). No azioni fisiche.' },
  { name:'Rimuovere Maledizione',     level:{chierico:3,paladino:3,bardo:3,inquisitore:3,mago:4,stregone:4,arcanista:4}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura o oggetto toccato', duration:'Istantanea', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Rimuove le maledizioni dal soggetto (anche multiple); non rimuove effetti basati su oggetti maledetti ancora indossati.' },
  { name:'Ondate di Fatica',          level:{mago:5,stregone:5,arcanista:5}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Cono 9 m', target:'Creature viventi nel cono', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'si', description:'Affatica tutti i bersagli nel cono (nessun TS); non affect già esausti.' },

  // ── Livello 6 — aggiunte ─────────────────────────────────────────────
  { name:'Globo di Invulnerabilità',  level:{mago:6,stregone:6,arcanista:6}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'10 piedi (3 m)', target:'Area sferica 3 m raggio centrata su incantatore', duration:'1 round/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Esclude tutti gli incantesimi di livello 1-4; Globo Inferiore blocca 1-3.' },
  { name:'Carne di Pietra',           level:{mago:6,stregone:6,arcanista:6,druido:7}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Media', target:'1 creatura', duration:'Permanente', savingThrow:'Fortitudine annulla', spellResistance:'si', description:'Trasforma la creatura in una statua di pietra (paralizzata, ma cosciente); reversibile con Pietra in Carne.' },
  { name:'Nube Nebbiosa Acida',       level:{mago:6,stregone:6,arcanista:6}, school:'Congiunzione', subschool:'Creazione', descriptor:'Acido', components:'V, S', castingTime:'1 azione standard', range:'Media', target:'Nube 6 m raggio', duration:'1 round/livello', savingThrow:'Fortitudine parziale', spellResistance:'no', description:'2d6 acido/round; causa 1 punto COS/round (TS Fortitudine annulla riduzione COS). La nube si sposta col vento a 3 m/round.' },
  { name:'Dominare i Mostri',         level:{mago:8,stregone:8,arcanista:8}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 round', range:'Corta', target:'1 mostro', duration:'1 giorno/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Come Dominare le Persone ma funziona su qualsiasi tipo di creatura.' },
  { name:'Suggestione di Massa',      level:{mago:6,stregone:6,arcanista:6,bardo:5}, school:'Ammaliamento', subschool:'Compulsione, Linguaggio, Mente', descriptor:'Mente', components:'V, M', castingTime:'1 azione standard', range:'Media', target:'1 creatura/livello in raggio 9 m', duration:'1 ora/livello o completata', savingThrow:'Volontà annulla', spellResistance:'si', description:'Come Suggestione ma funziona su più bersagli contemporaneamente.' },
  { name:'Eroismo Superiore',         level:{mago:6,stregone:6,arcanista:6,bardo:5}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'+4 morale a TxC, TS e tiri abilità; immunità a effetti di paura; +4 morale a prove abilità e +2 ai tiri abilità.' },
  { name:'Visione Vera',              level:{chierico:5,mago:6,stregone:6,arcanista:6,inquisitore:5}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 minuto/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Vede le illusioni per quello che sono, i polimorfati nella forma originale, piani interiori e invisibili entro 36 m.' },
  { name:'Simbolo della Paura',       level:{chierico:6,mago:6,stregone:6,arcanista:6}, school:'Necromanza', subschool:'', descriptor:'Paura, Mente, Male', components:'V, S, M', castingTime:'10 minuti', range:'0 m', target:'Segno creato', duration:'Vedi testo', savingThrow:'Volontà annulla', spellResistance:'si', description:'Glifo che spaventa (come incantesimo Paura) chi fallisce il TS per 1 round/livello.' },
  { name:'Cura Ferite Leggere di Massa', level:{chierico:5,druido:6,bardo:5,oracolo:5,sciamano:5}, school:'Congiunzione', subschool:'Guarigione', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura/livello in raggio 9 m', duration:'Istantanea', savingThrow:'Volontà dimezza (inanimato)', spellResistance:'si', description:'Cura 1d8+1/livello (max +25) a tutti gli alleati nel raggio; i nonmorti prendono danni.' },
  { name:'Infliggere Ferite Leggere di Massa', level:{chierico:5}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura/livello in raggio 9 m', duration:'Istantanea', savingThrow:'Volontà dimezza', spellResistance:'si', description:'Infligge 1d8+1/livello (max +25) a tutte le creature viventi nel raggio; cura i nonmorti.' },
  { name:'Barriera a Lame',           level:{mago:6,stregone:6,arcanista:6}, school:'Evocazione', subschool:'Creazione,Forza', descriptor:'Forza', components:'V, S', castingTime:'1 azione standard', range:'Media', target:'Muro di lame (max 2 m²/livello)', duration:'1 round/livello (dis.)', savingThrow:'Riflessi parziale', spellResistance:'si', description:'Muro di lame invisibili: 7d6 danni taglienti a chi attraversa (Riflessi dimezza).' },

];"""

with open(path, 'w') as f:
    f.write(content + ',\n' + new_block)

# Auto-fix apostrophes
import sys
sys.path.insert(0, os.path.dirname(__file__))

bad_pattern = chr(39) + chr(92) + chr(39)
good_escape = chr(92) + chr(39)
content2 = open(path).read()
header = content2[:200]
body = content2[200:]
import re
body_fixed = re.sub(r"(?<!\\)(?<=[a-zA-Zàèéìòùç])'(?=[a-zA-Zàèéìòùç])", lambda m: good_escape, body)
# Fix also the wrong '\ sequences if any
body_fixed2 = content2[200:].replace(bad_pattern, good_escape)
# Use the regex fix
result = header + body_fixed
open(path, 'w').write(result)

names = re.findall(r"name:'([^']+)'", open(path).read())
print(f"Done! Total spells now: {len(names)}")
