#!/usr/bin/env python3
"""Batch 2 — inserisce incantesimi livello 2 e 3 (aggiunte)."""
import os, re

path = os.path.join(os.path.dirname(__file__), '../js/data/spells-list.js')
content = open(path).read()
assert content.rstrip().endswith('];')
content = content.rstrip()[:-2].rstrip()

new_block = """
  // ── Livello 2 — aggiunte ─────────────────────────────────────────────
  { name:'Freccia Acida',            level:{mago:2,stregone:2,arcanista:2}, school:'Congiunzione', subschool:'Creazione,Acido', descriptor:'Acido', components:'V, S, M/F', castingTime:'1 azione standard', range:'Lunga (120 m + 12 m/livello)', target:'1 creatura', duration:'1 round + 1 round/3 livelli', savingThrow:'Nessuno', spellResistance:'si', description:'Raggio da tocco a distanza: 2d4 acido immediato + 2d4 acido per 1 round ogni 3 livelli.' },
  { name:'Mutare Forma',             level:{mago:2,stregone:2,arcanista:2,alchimista:2}, school:'Trasmutazione', subschool:'Polimorfismo', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1 minuto/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Trasformati in umanoide di taglia P o M diverso; guadagni +2 FOR o +2 DES e 5 res/danno.' },
  { name:'Serratura Arcana',         level:{mago:2,stregone:2,arcanista:2}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Porta, finestra o portello', duration:'Permanente', savingThrow:'Nessuno', spellResistance:'no', description:'Sbarra una porta magicamente: CD Forza +10, CD Aprire Serrature +10 rispetto ai valori normali.' },
  { name:'Vigore dell\'Orso',         level:{mago:2,stregone:2,arcanista:2,chierico:2,druido:2,ranger:2,alchimista:2}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 minuto/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'+4 potenziamento alla COS (+2 PF/DV, utile per TS Fortitudine).' },
  { name:'Cecità/Sordità',           level:{mago:2,stregone:2,arcanista:2,chierico:2,bardo:2}, school:'Necromanza', subschool:'', descriptor:'', components:'V', castingTime:'1 azione standard', range:'Media', target:'1 creatura vivente', duration:'Permanente (dis.)', savingThrow:'Fortitudine annulla', spellResistance:'si', description:'Acceca o assorda permanentemente il bersaglio (a scelta); rimovibile con Rimuovere Cecità/Sordità.' },
  { name:'Sfocatura',                level:{mago:2,stregone:2,arcanista:2}, school:'Illusione', subschool:'Figura', descriptor:'', components:'V', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1 minuto/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'20% di fallimento su ogni attacco contro l\'incantatore.' },
  { name:'Splendore dell\'Aquila',    level:{mago:2,stregone:2,arcanista:2,chierico:2,bardo:2,paladino:2,alchimista:2}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 minuto/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'+4 potenziamento al CAR (influisce su incantesimi, prove CAR).' },
  { name:'Vita Artificiale',         level:{mago:2,stregone:2,arcanista:2,alchimista:2}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1 ora/livello o finché si esauriscono i PF bonus', savingThrow:'Nessuno', spellResistance:'no', description:'Guadagni 1d10+1/livello PF temporanei (max +10); spariscono quando la durata scade.' },
  { name:'Sfera di Fuoco',           level:{mago:2,stregone:2,arcanista:2,druido:2}, school:'Evocazione', subschool:'', descriptor:'Fuoco', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Media', target:'Sfera di 1,5 m di raggio', duration:'1 round/livello', savingThrow:'Riflessi annulla', spellResistance:'si', description:'Una sfera rotolante di fuoco; 2d6 danni fuoco alle creature che tocca; puoi muoverla 9 m per round come azione movimento.' },
  { name:'Visione nel Buio',         level:{mago:2,stregone:2,arcanista:2,ranger:3,alchimista:2,inquisitore:2}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 ora/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Il soggetto ottiene vista al buio fino a 18 m per la durata.' },
  { name:'Raggio Rovente',           level:{mago:2,stregone:2,arcanista:2,magus:2}, school:'Evocazione', subschool:'', descriptor:'Fuoco', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'Fino a 3 raggi', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'si', description:'Da 1 a 3 raggi (uno ogni 4 livelli, max 3): ciascuno 4d6 danni fuoco su attacco da tocco a distanza.' },
  { name:'Vedere l\'Invisibile',     level:{mago:2,stregone:2,arcanista:2,bardo:3,alchimista:2}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'10 minuti/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Vedi le creature e gli oggetti invisibili come se non lo fossero.' },
  { name:'Ragnatela',                level:{mago:2,stregone:2,arcanista:2}, school:'Congiunzione', subschool:'Creazione', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Media', target:'Area in raggio 6 m', duration:'10 minuti/livello (dis.)', savingThrow:'Riflessi annulla (vedi testo)', spellResistance:'no', description:'Riempie l\'area di ragnatele; terreno difficile e rischio intralcio (Forza CD 20 per sfuggire o bruciare).' },
  { name:'Resistere all\'Energia',   level:{mago:2,stregone:2,arcanista:2,chierico:2,druido:2,ranger:1,paladino:2,alchimista:2}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Fortitudine annulla (innocuo)', spellResistance:'si', description:'Resistenza 10 contro fuoco, freddo, elettricità, acido o sonoro (aumenta con livello).' },
  { name:'Trucco della Corda',       level:{mago:2,stregone:2,arcanista:2}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'1 corda lunga 1,5–9 m', duration:'1 ora/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'La corda si erge verticalmente e apre un extradimensionale spazio per 8 persone all\'estremità superiore.' },
  { name:'Immagine Minore',          level:{mago:2,stregone:2,arcanista:2,bardo:2}, school:'Illusione', subschool:'Figura', descriptor:'', components:'V, S, F', castingTime:'1 azione standard', range:'Lunga (120 m + 12 m/livello)', target:'Immagine con effetti sonori (max 1,5 m c/livello)', duration:'Concentrazione + 2 round', savingThrow:'Indagare annulla', spellResistance:'no', description:'Come Immagine Silenziosa ma aggiunge effetti sonori alla figura visiva.' },
  { name:'Protezione dalle Frecce',  level:{mago:2,stregone:2,arcanista:2}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 ora/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'DR 10/magia contro armi da distanza fisiche.' },
  { name:'Pirotecnica',              level:{mago:2,stregone:2,arcanista:2,bardo:2}, school:'Trasmutazione', subschool:'', descriptor:'Fuoco', components:'V, S, M', castingTime:'1 azione standard', range:'Lunga', target:'1 fuoco di taglia P o più', duration:'Concentrazione + 1 round, o 1d4+1 round', savingThrow:'Volontà annulla (vedi testo)', spellResistance:'si', description:'Trasforma un fuoco in segnale fumogeno accecante o in fuochi d\'artificio; acceca nel raggio 30 m.' },
  { name:'Aprire le Serrature',      level:{mago:2,stregone:2,arcanista:2}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Media', target:'1 oggetto bloccato', duration:'Istantanea', savingThrow:'Volontà annulla (oggetto)', spellResistance:'si', description:'Apre porte, serrature, portafogli e oggetti chiusi (trattandoli come Aprire Serratura con BdI pari al tuo livello incantatore).' },
  { name:'Arrampicarsi sulle Pareti', level:{mago:2,stregone:2,arcanista:2,druido:2,ranger:2,alchimista:2}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Il soggetto si arrampica come un ragno: velocità di scalata 6 m; non richiede prove.' },
  { name:'Vento Sussurrante',        level:{mago:2,stregone:2,arcanista:2,bardo:3}, school:'Trasmutazione', subschool:'', descriptor:'Aria, Linguaggio', components:'V, S', castingTime:'1 azione standard', range:'Lunga', target:'', duration:'No più di 1 ora/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Invia un messaggio sonoro silenzioso verso un luogo familiare; può portare 25 parole.' },
  { name:'Riso Isterico',            level:{mago:2,stregone:2,arcanista:2,bardo:1}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S, M', castingTime:'1 azione standard', range:'Corta', target:'1 creatura/3 livelli in raggio 9 m', duration:'1 round/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'I bersagli sono sopraffatti dal ridere (prono, -4 a TxC, TS e CA).' },
  { name:'Individuare Oggetti',      level:{mago:2,stregone:2,arcanista:2,bardo:2,chierico:3,inquisitore:2}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S, F/DF', castingTime:'1 azione standard', range:'Lunga', target:'Cerchio di 30 m di raggio', duration:'1 minuto/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Senti la direzione di un oggetto familiare o tipo di oggetto entro il raggio.' },
  { name:'Calore del Metallo',       level:{druido:2}, school:'Trasmutazione', subschool:'', descriptor:'Fuoco', components:'V, S, DF', castingTime:'1 azione standard', range:'Corta', target:'Metallo indossato o portato da max 1 creatura/2 livelli', duration:'7 round', savingThrow:'Volontà annulla (oggetto)', spellResistance:'si', description:'Surriscalda il metallo: 1° round nessun danno, 2°-3° 1d4, 4° 2d4, 5°-6° 1d4, 7° nessun danno; chi tiene perde presa.' },
  { name:'Individuare Trappole',     level:{chierico:2,inquisitore:2}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'', duration:'1 minuto/livello', savingThrow:'Nessuno', spellResistance:'no', description:'+10 competenza a Percezione per individuare trappole entro 18 m.' },
  { name:'Tocco dell\'Idiozia',      level:{mago:2,stregone:2,arcanista:2}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'-1d6 a INT, SAG e CAR (riduzione a 1 minimo); blocca la preparazione di incantesimi.' },

  // ── Livello 3 — aggiunte ──────────────────────────────────────────────
  { name:'Bloccare le Persone',      level:{mago:3,stregone:3,arcanista:3,chierico:2,inquisitore:2,bardo:2}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S, F/DF', castingTime:'1 azione standard', range:'Media', target:'1 o più umanoidi, nessuno oltre 9 m dall\'altro', duration:'1 round/livello (dis.)', savingThrow:'Volontà annulla', spellResistance:'si', description:'Paralizza umanoidi bersaglio per la durata; un\'azione Standard per paralizzarne uno, un\'azione completa per tentare più bersagli.' },
  { name:'Sonno Profondo',           level:{mago:3,stregone:3,arcanista:3,bardo:3}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S, M', castingTime:'1 round', range:'Media', target:'Creature viventi in raggio 9 m con max 10 DV', duration:'10 minuti/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Come Sonno ma ha effetto su 10 DV totali; le creature dormono profondamente.' },
  { name:'Visione Arcana',           level:{mago:3,stregone:3,arcanista:3}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1 minuto/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Vedi le aure magiche entro 36 m; come Individuare Magia ma sempre attivo e a raggio maggiore.' },
  { name:'Chiaroudito/Chiaroveggenza', level:{mago:3,stregone:3,arcanista:3,bardo:3}, school:'Divinazione', subschool:'Sfera Cristallina', descriptor:'', components:'V, S, F/M', castingTime:'10 minuti', range:'Lunga (120 m + 12 m/livello)', target:'', duration:'1 minuto/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Crea un sensore invisibile che ti permette di vedere o sentire un luogo familiare entro il raggio.' },
  { name:'Luce Diurna',              level:{chierico:3,druido:3,bardo:3,paladino:3,inquisitore:3,mago:3,stregone:3,arcanista:3}, school:'Evocazione', subschool:'', descriptor:'Luce', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Oggetto toccato', duration:'10 minuti/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Luce intensa come la luce solare in raggio 18 m; annulla le tenebre magiche fino al 2° livello.' },
  { name:'Rune Esplosive',           level:{mago:3,stregone:3,arcanista:3}, school:'Abiurazione', subschool:'', descriptor:'Forza', components:'V, S', castingTime:'1 azione standard', range:'0 m', target:'Un oggetto toccato pesante fino a 5 kg', duration:'Permanente fino a scatenata', savingThrow:'Riflessi parziale', spellResistance:'si', description:'Traccia rune invisibili su un oggetto; scoppiano quando lette o aperto il libro: 6d6 danni forza, 3 m raggio (Riflessi dimezza).' },
  { name:'Eroismo',                  level:{mago:3,stregone:3,arcanista:3,bardo:2}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'+2 morale ai TxC, TS e tiri abilità.' },
  { name:'Suggestione',              level:{mago:3,stregone:3,arcanista:3,bardo:2,inquisitore:3}, school:'Ammaliamento', subschool:'Linguaggio, Mente, Compulsione', descriptor:'Mente', components:'V, M', castingTime:'1 azione standard', range:'Corta', target:'1 creatura vivente', duration:'1 ora/livello o finché completata', savingThrow:'Volontà annulla', spellResistance:'si', description:'Il bersaglio segue un\'azione suggerita che non sembri ovviamente pericolosa.' },
  { name:'Lingue',                   level:{mago:3,stregone:3,arcanista:3,bardo:2,chierico:4}, school:'Divinazione', subschool:'', descriptor:'Linguaggio', components:'V, M/DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'no', description:'Il soggetto capisce e parla qualsiasi linguaggio.' },
  { name:'Rallentare',               level:{mago:3,stregone:3,arcanista:3}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Corta', target:'1 creatura/livello in raggio 9 m', duration:'1 round/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Il bersaglio agisce come se sotto l\'effetto opposto di Velocità: -1 TxC e CA, 1 azione standard/round, dimezza le mosse bonus.' },
  { name:'Nuvola Maleodorante',      level:{mago:3,stregone:3,arcanista:3}, school:'Congiunzione', subschool:'Creazione', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Corta', target:'Nuvola di vapori 6 m raggio', duration:'1 round/livello', savingThrow:'Fortitudine annulla (vedi testo)', spellResistance:'no', description:'Gas nauseante: gli esseri all\'interno devono superare Fortitudine o essere nauseati (solo distolti per 1 round se passano il TS).' },
  { name:'Tocco Vampirico',          level:{mago:3,stregone:3,arcanista:3,magus:3}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura vivente', duration:'Istantanea/1 ora', savingThrow:'Nessuno', spellResistance:'si', description:'1d6/2 livelli (max 10d6) danni da tocco; l\'incantatore guadagna i PF persi (fino al suo max) come PF temporanei per 1 ora.' },
  { name:'Protezione dall\'Energia', level:{mago:3,stregone:3,arcanista:3,chierico:3,druido:3,ranger:2,paladino:3,inquisitore:3}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello o finché i danni sono assorbiti', savingThrow:'Fortitudine annulla (innocuo)', spellResistance:'si', description:'Assorbe 12 danni/livello (max 120) di un tipo scelto di energia (fuoco, freddo, ecc.).' },
  { name:'Cerchio Magico contro il Male', level:{mago:3,stregone:3,arcanista:3,chierico:3,paladino:3,inquisitore:3}, school:'Abiurazione', subschool:'', descriptor:'Bene', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'no', description:'Come Protezione dal Male ma in raggio 3 m; crea area di protezione e può contenere evocazioni malvagie.' },
  { name:'Cavalcatura Fantasma',     level:{mago:3,stregone:3,arcanista:3}, school:'Congiunzione', subschool:'Creazione', descriptor:'', components:'V, S', castingTime:'10 minuti', range:'0 m', target:'Destriero evocato', duration:'1 ora/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Crea un destriero magico con CA 18, 7 PF, velocità 24 m, che svanisce se ucciso.' },
  { name:'Rimpicciolire Oggetto',    level:{mago:3,stregone:3,arcanista:3}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'1 oggetto da max 2 kg/livello', duration:'1 giorno/livello (dis.)', savingThrow:'Volontà annulla (oggetto)', spellResistance:'si', description:'Riduce un oggetto a 1/16 delle dimensioni e 1/1000 del peso; può essere restituito alla normalità.' },
  { name:'Maledizione',              level:{mago:3,stregone:3,arcanista:3,chierico:3,inquisitore:3,bardo:3}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'Permanente', savingThrow:'Volontà annulla', spellResistance:'si', description:'Impone una delle seguenti maledizioni: -6 a una caratteristica; -4 ai TxC, TS e prove; 50% fallimento azioni.' },
  { name:'Fermare i Nonmorti',       level:{mago:3,stregone:3,arcanista:3}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Corta', target:'Max 3 nonmorti', duration:'1 round/livello', savingThrow:'Volontà parziale', spellResistance:'si', description:'Paralizza i nonmorti bersaglio; fallito TS = immobili (Paralizzati); superato TS = solo -2 a TxC, CA e prove di abilità.' },
  { name:'Non-Individuazione',       level:{mago:3,stregone:3,arcanista:3,ranger:4}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Creatura o oggetto toccato', duration:'1 ora/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'no', description:'Protegge da Individuare Magia e simili; per sferare il velo richiede una prova CL vs. CD 11+livello.' },
  { name:'Animare i Morti',          level:{chierico:3,mago:4,stregone:4,arcanista:4}, school:'Necromanza', subschool:'', descriptor:'Male', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'1 o più cadaveri', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'no', description:'Anima scheletri o zombie dai cadaveri (max DV pari al tuo doppio livello).' },
  { name:'Preghiera',                level:{chierico:3,paladino:3,inquisitore:3}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S, DF', castingTime:'1 azione standard', range:'Corta', target:'Alleati e nemici in raggio 9 m', duration:'1 round/livello', savingThrow:'Nessuno', spellResistance:'si', description:'+1 sacralità a TxC, danni, TS e prove agli alleati; -1 profano agli stessi valori ai nemici.' },
  { name:'Respirare Sott\'Acqua',   level:{chierico:3,druido:3,mago:3,stregone:3,arcanista:3,ranger:3,alchimista:2}, school:'Trasmutazione', subschool:'', descriptor:'Acqua', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Tocco', target:'1 creatura/livello toccata', duration:'2 ore/livello; divisibile per numero di creature', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Le creature bersaglio possono respirare sott\'acqua per la durata.' },
  { name:'Muro di Vento',            level:{chierico:3,druido:3,mago:3,stregone:3,arcanista:3,ranger:2}, school:'Evocazione', subschool:'', descriptor:'Aria', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Media', target:'Muro di vento 3 m altezza, 1 m larghezza/livello', duration:'1 round/livello (dis.)', savingThrow:'Vedi testo', spellResistance:'si', description:'Vento tempestoso blocca piccoli proiettili, nebbie per metà; creatura taglia P o M deve superare Forza per passare.' },
  { name:'Contagio',                 level:{chierico:3,druido:3,mago:4,stregone:4,arcanista:4}, school:'Necromanza', subschool:'', descriptor:'Male', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'Istantanea', savingThrow:'Fortitudine annulla', spellResistance:'si', description:'Causa una malattia magica nel bersaglio (scegli tra varie; incubazione immediata).' },
  { name:'Rimuovere Cecità/Sordità', level:{chierico:3,paladino:3,inquisitore:3}, school:'Congiunzione', subschool:'Guarigione', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'Istantanea', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Cura cecità o sordità (sia normale che magica).' },
  { name:'Rimuovere Malattia',       level:{chierico:3,druido:3,ranger:3,inquisitore:3}, school:'Congiunzione', subschool:'Guarigione', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'Istantanea', savingThrow:'Fortitudine annulla (innocuo)', spellResistance:'si', description:'Cura ogni malattia naturale o magica che affligge il soggetto.' },
  { name:'Chiamata dei Fulmini',     level:{druido:3}, school:'Evocazione', subschool:'', descriptor:'Elettricità', components:'V, S', castingTime:'1 round', range:'Media', target:'Nuvola di 36 m raggio, 12 m altezza', duration:'1 minuto/livello', savingThrow:'Riflessi dimezza', spellResistance:'si', description:'Invoca fulmini dal cielo (o soffitto): un fulmine da 3d6 elettricità per round come azione standard.' },
  { name:'Crescita delle Piante',    level:{druido:3,ranger:3}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Corta o Lunga', target:'Piante in area ampia', duration:'Permanente', savingThrow:'Nessuno', spellResistance:'no', description:'Fa crescere piante selvatiche: crea terreno difficile (area fittamente ricoperta), o aumenta la resa agricola.' },
  { name:'Arma Magica Superiore',    level:{chierico:4,paladino:3,mago:3,stregone:3,arcanista:3,inquisitore:3,magus:3}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Corta', target:'1 arma o 50 proiettili (tutti in contatto)', duration:'1 ora/livello', savingThrow:'Volontà annulla (inanimato)', spellResistance:'no', description:'+1/4 livelli di bonus a potenziamento (max +5) all\'arma bersaglio.' },

];"""

with open(path, 'w') as f:
    f.write(content + ',\n' + new_block)

import re
names = re.findall(r"name:'([^']+)'", open(path).read())
print(f"Done! Total spells now: {len(names)}")
