#!/usr/bin/env python3
"""Batch 4 — incantesimi livello 7, 8 e 9 (aggiunte)."""
import os, re

path = os.path.join(os.path.dirname(__file__), '../js/data/spells-list.js')
content = open(path).read()
assert content.rstrip().endswith('];')
content = content.rstrip()[:-2].rstrip()

new_block = """
  // ── Livello 7 — aggiunte ─────────────────────────────────────────────
  { name:'Raggio Prismatico',        level:{mago:7,stregone:7,arcanista:7}, school:'Evocazione', subschool:'', descriptor:'Luce', components:'V, S', castingTime:'1 azione standard', range:'Cono 18 m', target:'Creature nel cono', duration:'Istantanea', savingThrow:'Vedi testo', spellResistance:'si', description:'8 raggi colorati: rosso(2d4 fuoco), arancio(4d6 acido), giallo(8d6 elettricità), verde(veleno), blu(pietrificazione), indaco(pazzia), viola(cambio piano), ottavo(2 raggi).' },
  { name:'Deviare Incantesimi',      level:{mago:7,stregone:7,arcanista:7}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'Fino a 20 livelli di incantesimi riflessi', savingThrow:'Nessuno', spellResistance:'no', description:'Ritorna 1d4+6 livelli di incantesimi bersaglio verso l\'originale incantatore (5% chance per ogni raggio).' },
  { name:'Bando',                    level:{mago:7,stregone:7,arcanista:7,chierico:6,inquisitore:6}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'Max 2 DV/livello di creature extradimensionali', duration:'Istantanea', savingThrow:'Volontà annulla', spellResistance:'si', description:'Espelle creature extradimensionali nel loro piano di origine (le più deboli per prime).' },
  { name:'Legame Telepatico',        level:{mago:5,stregone:5,arcanista:5}, school:'Divinazione', subschool:'', descriptor:'(Mente)', components:'V, S, M', castingTime:'1 minuto', range:'Corta', target:'1 creatura/3 livelli in raggio 9 m', duration:'10 minuti/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'no', description:'Collega telepaticamente le creature bersaglio; comunicazione mentale tra tutte per la durata.' },
  { name:'Parola di Potere Accecante', level:{mago:7,stregone:7,arcanista:7}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Linguaggio, Mente', components:'V', castingTime:'1 azione standard', range:'Corta', target:'1 creatura', duration:'Vedi testo', savingThrow:'Nessuno', spellResistance:'si', description:'Acceca permanentemente (<= 200 PF), o per 1d4+1 min (201-400 PF), o 1d4 round (> 400 PF).' },
  { name:'Simulacro',                level:{mago:7,stregone:7,arcanista:7}, school:'Illusione', subschool:'Ombra', descriptor:'(Freddo)', components:'V, S, M, F', castingTime:'12 ore', range:'0 m', target:'1 copia della creatura', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'no', description:'Crea una copia illusoria funzionante con il 51-100% dei PF originali e la stessa memoria operativa; obbedisce ai tuoi comandi.' },
  { name:'Scrutare Superiore',       level:{mago:7,stregone:7,arcanista:7,chierico:7,druido:7}, school:'Divinazione', subschool:'Sfera Cristallina', descriptor:'', components:'V, S, M/DF/F', castingTime:'1 ora', range:'Vedi testo', target:'1 creatura', duration:'1 ora/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Come Scrying ma dura 1 ora/livello e il CD del TS è maggiore.' },
  { name:'Proiezione Astrale',       level:{chierico:9,mago:9,stregone:9,arcanista:9}, school:'Congiunzione', subschool:'Teletrasporto', descriptor:'', components:'V, S, M/DF', castingTime:'30 minuti', range:'Tocco', target:'Tu e max 8 creatura toccat', duration:'Vedi testo', savingThrow:'Nessuno', spellResistance:'si', description:'Proietta il corpo astrale nel Piano Astrale; corpo fisico rimane in trance fino al ritorno o alla morte.' },
  { name:'Cambio Planare',           level:{chierico:5,mago:7,stregone:7,arcanista:7,inquisitore:5}, school:'Congiunzione', subschool:'Teletrasporto', descriptor:'', components:'V, S, F/DF', castingTime:'1 azione standard', range:'Tocco', target:'Tu e max 8 creature toccat', duration:'Istantanea', savingThrow:'Volontà annulla', spellResistance:'si', description:'Trasporta o espelle (TS annulla) max 8 creature verso un piano di esistenza che conosci.' },

  // ── Livello 8 — aggiunte ─────────────────────────────────────────────
  { name:'Avvizzimento Orrendo',     level:{mago:8,stregone:8,arcanista:8}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Media', target:'Creature viventi in raggio 6 m', duration:'Istantanea', savingThrow:'Fortitudine parziale', spellResistance:'si', description:'3d6 COS ai bersagli (Fortitudine dimezza); dissecca i fluidi vitali. Non funziona su piante, creature acquatiche, ecc.' },
  { name:'Nube Incendiaria',         level:{mago:8,stregone:8,arcanista:8}, school:'Congiunzione', subschool:'Creazione', descriptor:'Fuoco', components:'V, S', castingTime:'1 azione standard', range:'Media', target:'Nube 6 m raggio', duration:'1 round/livello', savingThrow:'Riflessi dimezza', spellResistance:'si', description:'6d6 danni fuoco/round a creature nella nube; si disperde in vento moderato.' },
  { name:'Labirinto',                level:{mago:8,stregone:8,arcanista:8}, school:'Congiunzione', subschool:'Teletrasporto', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura', duration:'Finché non esce', savingThrow:'Nessuno', spellResistance:'si', description:'Spedisce la creatura in un labirinto extradimensionale; per uscire INT CD 20 (1 round) o 10 minuti di tentativi; minotauri escono subito.' },
  { name:'Mente Bianca',             level:{mago:8,stregone:8,arcanista:8}, school:'Abiurazione', subschool:'', descriptor:'(Mente)', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 giorno/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Immunita a quasi tutti gli incantesimi e gli effetti mentali; blocca indagini psioniche e divinazioni sul soggetto.' },
  { name:'Esplosione Solare',        level:{mago:8,stregone:8,arcanista:8,druido:8}, school:'Evocazione', subschool:'', descriptor:'Luce', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'Sfera 18 m raggio', duration:'Istantanea', savingThrow:'Riflessi parziale e Fortitudine parziale', spellResistance:'si', description:'6d6 danni fuoco a tutte le creature (Riflessi dimezza); acceca permanentemente chi fallisce la Fortitudine (cecità curable).' },
  { name:'Stasi Temporale',          level:{mago:8,stregone:8,arcanista:8}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'Permanente', savingThrow:'Fortitudine annulla', spellResistance:'si', description:'Pone il bersaglio in animazione sospesa (come petrificazione ma senza peso); non invecchia ne soffre. Reversibile con Libertà.' },
  { name:'Simbolo della Morte',      level:{chierico:8,mago:8,stregone:8,arcanista:8}, school:'Necromanza', subschool:'', descriptor:'Male, Morte', components:'V, S, M', castingTime:'10 minuti', range:'0 m', target:'Segno creato', duration:'Vedi testo', savingThrow:'Fortitudine annulla', spellResistance:'si', description:'Glifo che uccide istantaneamente le creature (max 150 PF totali) che lo leggono; funziona 10 minuti/livello.' },
  { name:'Sfera Telecinetica',        level:{mago:8,stregone:8,arcanista:8}, school:'Evocazione', subschool:'Creazione,Forza', descriptor:'Forza', components:'V, S, F', castingTime:'1 azione standard', range:'Corta', target:'Max 1 creatura/3 livelli di taglia G o meno', duration:'1 minuto/livello', savingThrow:'Riflessi annulla', spellResistance:'si', description:'Intrappola le creature in sfere di forza impenetrabili; le sfere si muovono con telechinesi.' },
  { name:'Raggio Polare',            level:{mago:8,stregone:8,arcanista:8}, school:'Evocazione', subschool:'', descriptor:'Freddo', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 raggio', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'si', description:'Raggio da tocco a distanza: 1d6/livello danni freddo (max 25d6) + 2d4 degradazione DES.' },

  // ── Livello 9 — aggiunte ─────────────────────────────────────────────
  { name:'Arresto del Tempo',        level:{mago:9,stregone:9,arcanista:9}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1d4+1 round (percepiti)', savingThrow:'Nessuno', spellResistance:'no', description:'Tempo si ferma per tutti eccetto l\'incantatore per 1d4+1 round (soggettivi); non puoi attaccare creature congelate ma puoi prepararti.' },
  { name:'Urlo della Banshee',       level:{mago:9,stregone:9,arcanista:9}, school:'Necromanza', subschool:'', descriptor:'Morte, Suono', components:'V', castingTime:'1 azione standard', range:'Corta', target:'Max 1 creatura/livello in raggio 9 m', duration:'Istantanea', savingThrow:'Fortitudine annulla', spellResistance:'si', description:'Uccide istantaneamente i bersagli che falliscono il TS Fortitudine.' },
  { name:'Parola di Potere Mortale', level:{mago:9,stregone:9,arcanista:9}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Linguaggio, Mente, Morte', components:'V', castingTime:'1 azione standard', range:'Corta', target:'1 creatura vivente', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'si', description:'Uccide istantaneamente la creatura bersaglio se ha 100 o meno PF; nessun TS.' },
  { name:'Imprigionamento',          level:{mago:9,stregone:9,arcanista:9}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'1 creatura', duration:'Permanente', savingThrow:'Volontà annulla', spellResistance:'si', description:'Imprigiona permanentemente il bersaglio in cristallo sotterraneo (dormiente, non invecchia); liberabile con Libertà.' },
  { name:'Disgiunzione',             level:{mago:9,stregone:9,arcanista:9}, school:'Abiurazione', subschool:'', descriptor:'', components:'V', castingTime:'1 azione standard', range:'Corta', target:'Tutti gli oggetti magici in raggio 6 m e la magia attiva sulle creature', duration:'Istantanea', savingThrow:'Volontà annulla (oggetto)', spellResistance:'no', description:'Distrugge gli incantesimi attivi sulle creature e rimuove le proprietà magiche dagli oggetti (1% chance per livello per ogni oggetto).' },
  { name:'Portale',                  level:{chierico:9,mago:9,stregone:9,arcanista:9}, school:'Congiunzione', subschool:'Richiamo,Creazione', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Media', target:'Portale circolare fino a 6 m diametro', duration:'Concentrazione + 2 round/livello o concentrazione', savingThrow:'Nessuno', spellResistance:'no', description:'Apre un portale verso un altro piano; può evocare potenti creature (DV pari o inferiori ai tuoi livelli).' },
  { name:'Sfera Prismatica',         level:{mago:9,stregone:9,arcanista:9}, school:'Abiurazione', subschool:'', descriptor:'Luce', components:'V', castingTime:'1 azione standard', range:'10 piedi (3 m)', target:'Sfera di raggio 10 piedi attorno all\'incantatore', duration:'10 minuti/livello (dis.)', savingThrow:'Vedi testo', spellResistance:'si', description:'Sfera di 8 strati di protezione (come Raggio Prismatico); chi cerca di attraversarla subisce tutti gli effetti in sequenza.' },
  { name:'Forma del Cambiamento',    level:{druido:9,mago:9,stregone:9,arcanista:9}, school:'Trasmutazione', subschool:'Polimorfismo', descriptor:'', components:'V, S, F', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1 ora/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Trasformati in qualsiasi creatura con DV max 25; guadagni le caratteristiche fisiche e le abilità speciali della forma scelta.' },
  { name:'Drenare Energia',          level:{chierico:9,mago:9,stregone:9,arcanista:9}, school:'Necromanza', subschool:'', descriptor:'Male', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura vivente', duration:'Istantanea', savingThrow:'Fortitudine parziale', spellResistance:'si', description:'2d4 livelli negativi al bersaglio (TS Fortitudine dimezza); permanenti (CD TS = 25 per ogni livello negativo).' },

];"""

with open(path, 'w') as f:
    f.write(content + ',\n' + new_block)

# Auto-fix apostrophes using correct method
content2 = open(path).read()
bad_pattern = chr(39) + chr(92) + chr(39)  # '\'
good_escape = chr(92) + chr(39)             # \'
header = content2[:200]
body = content2[200:]
pattern = r"(?<!\\)(?<=[a-zA-Zàèéìòùç])'(?=[a-zA-Zàèéìòùç])"
body_fixed = re.sub(pattern, lambda m: good_escape, body)
result = header + body_fixed
open(path, 'w').write(result)

names = re.findall(r"name:'([^']+)'", open(path).read())
print(f"Done! Total spells now: {len(names)}")
