#!/usr/bin/env python3
"""Batch 1 — inserisce incantesimi livello 0 e 1 (aggiunte) nel PF1_SPELLS_DB."""
import os

path = os.path.join(os.path.dirname(__file__), '../js/data/spells-list.js')
content = open(path).read()
assert content.rstrip().endswith('];'), "File non termina con ];"
content = content.rstrip()[:-2].rstrip()  # rimuovi `];` finale

new_block = """
  // ── Livello 0 — aggiunte ─────────────────────────────────────────────
  { name:'Schizzo Acido',           level:{mago:0,stregone:0,arcanista:0}, school:'Congiunzione', subschool:'Creazione,Acido', descriptor:'Acido', components:'V, S', castingTime:'1 azione standard', range:'Corta (7,5 m + 1,5 m/2 livelli)', target:'1 creatura o oggetto', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'no', description:'Attacco a distanza da tocco: 1d3 danni acido.' },
  { name:'Segno Arcano',             level:{mago:0,stregone:0,arcanista:0}, school:'Universale', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'0 m', target:'Un\'area fino a 0,3 m²', duration:'Permanente', savingThrow:'Nessuno', spellResistance:'no', description:'Scrive il tuo segno o simbolo personale, visibile o invisibile, su una superficie.' },
  { name:'Sanguinante',              level:{mago:0,stregone:0,arcanista:0,druido:0,chierico:0}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura vivente', duration:'Concentrazione (max 1 round/livello)', savingThrow:'Volontà annulla', spellResistance:'si', description:'Fa sanguinare una creatura ferita: 1 danno all\'inizio del suo turno.' },
  { name:'Fiaccole Danzanti',        level:{mago:0,stregone:0,arcanista:0,bardo:0}, school:'Evocazione', subschool:'', descriptor:'Luce', components:'V, S', castingTime:'1 azione standard', range:'Media (30 m + 3 m/livello)', target:'Fino a 4 torce o luci', duration:'1 minuto (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Crea fino a 4 fiamme danzanti che iluminano come torce; puoi muoverle con un\'azione libera.' },
  { name:'Stordimento',              level:{mago:0,stregone:0,arcanista:0,bardo:0}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 umanoide con 4 DV o meno', duration:'1 round', savingThrow:'Volontà annulla', spellResistance:'si', description:'Stordisce (non può agire) un umanoide debole per 1 round.' },
  { name:'Individuare i Veleni',     level:{mago:0,stregone:0,arcanista:0,chierico:0,druido:0,paladino:1,ranger:1}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'1 creatura, oggetto o cubetto di 1,5 m', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'no', description:'Individua i veleni in un oggetto o creatura e il tipo di veleno se superi una prova di Conoscenze (natura) CD 20.' },
  { name:'Bagliore',                  level:{mago:0,stregone:0,arcanista:0,druido:0,bardo:0}, school:'Evocazione', subschool:'', descriptor:'Luce', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura', duration:'Istantanea', savingThrow:'Riflessi annulla', spellResistance:'si', description:'Acceca brevemente il bersaglio: -1 ai tiri per colpire fino alla fine del suo prossimo turno.' },
  { name:'Suono Fantasma',           level:{mago:0,stregone:0,arcanista:0,bardo:0}, school:'Illusione', subschool:'Figura', descriptor:'Suono', components:'V, S, M', castingTime:'1 azione standard', range:'Lunga (120 m + 12 m/livello)', target:'Emanazione legato a un oggetto o luogo', duration:'Concentrazione (1 round/livello)', savingThrow:'Indagare annulla', spellResistance:'no', description:'Crea un suono illusorio della potenza di 4 persone (o superiore con livelli maggiori).' },
  { name:'Mano del Mago',            level:{mago:0,stregone:0,arcanista:0,bardo:0}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 oggetto fino a 2,5 kg', duration:'Concentrazione', savingThrow:'Nessuno', spellResistance:'no', description:'Muovi telecineticamente un oggetto a 4,5 m per round; non puoi usarlo per attaccare.' },
  { name:'Messaggio',                level:{mago:0,stregone:0,arcanista:0,bardo:0}, school:'Trasmutazione', subschool:'', descriptor:'Linguaggio', components:'V, S, F', castingTime:'1 azione standard', range:'Media', target:'1 creatura/livello', duration:'10 minuti/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Sussurri a distanza: la creatura designata ti sente e può risponderti sottovoce.' },
  { name:'Aprire/Chiudere',          level:{mago:0,stregone:0,arcanista:0,bardo:0}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, F', castingTime:'1 azione standard', range:'Corta', target:'Oggetto pesante max 14 kg', duration:'Istantanea', savingThrow:'Volontà annulla (oggetto)', spellResistance:'si', description:'Apre o chiude a distanza porte, finestre, borse non bloccate da magia.' },
  { name:'Leggere la Magia',         level:{mago:0,stregone:0,arcanista:0,bardo:0,chierico:0,druido:0,paladino:1,ranger:1}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S, F', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'10 minuti/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Leggi pergamene magiche, libri degli incantesimi e iscrizioni magiche. Puoi identificare i glifi.' },
  { name:'Creare Acqua',             level:{chierico:0,druido:0,paladino:1,ranger:2}, school:'Congiunzione', subschool:'Creazione', descriptor:'Acqua', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'Max 1 kg d\'acqua/2 livelli', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'no', description:'Crea acqua potabile (4 litri/livello) in un contenitore aperto.' },
  { name:'Purificare Cibo e Bevande', level:{chierico:0,druido:0}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 cubetto di 0,3 m lato di cibo/bevande', duration:'Istantanea', savingThrow:'Volontà annulla (oggetto)', spellResistance:'no', description:'Rende commestibile e potabile del cibo o acqua avariati/avvelenati.' },
  { name:'Stabilizzare',             level:{chierico:0,druido:0}, school:'Congiunzione', subschool:'Guarigione', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura vivente ferita', duration:'Istantanea', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Stabilizza immediatamente una creatura morente (interrompe i tiri di stabilizzazione).' },
  { name:'Vigore',                   level:{chierico:0,druido:0}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 minuto', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'+1 ai Tiri Salvezza (bonus di sacralità/profano: varia per fonte).' },
  { name:'Ninna Nanna',              level:{bardo:0}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V', castingTime:'1 azione standard', range:'Corta', target:'Creature viventi in raggio 9 m', duration:'Concentrazione + 1 round/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Le creature bersaglio diventano assonnate (-5 alle prove di Percezione).' },
  { name:'Evocare Strumento',        level:{bardo:0}, school:'Congiunzione', subschool:'Richiamo', descriptor:'', components:'V, S', castingTime:'1 azione libera', range:'0 m', target:'Strumento musicale', duration:'1 minuto/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Evoca uno strumento musicale non magico a scelta.' },
  { name:'Individuare la Direzione', level:{bardo:0,druido:0}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'no', description:'Conosci immediatamente quale direzione è il nord.' },
  { name:'Danneggiare i Nonmorti',   level:{mago:0,stregone:0,arcanista:0,chierico:0}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura non morta', duration:'Istantanea', savingThrow:'Nessuno', spellResistance:'si', description:'Attacco a distanza da tocco contro i nonmorti: 1d6 danni +1/livello (max 5d6); non funziona su creature viventi.' },

  // ── Livello 1 — aggiunte ──────────────────────────────────────────────
  { name:'Allarme',                  level:{mago:1,stregone:1,arcanista:1,ranger:1,inquisitore:1}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, F/DF', castingTime:'1 azione standard', range:'Corta', target:'Area in raggio 6 m dal punto', duration:'2 ore/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Imposta un allarme mentale o uditivo: risuona se creatura taglia il perimetro.' },
  { name:'Mani Fiammate',            level:{mago:1,stregone:1,arcanista:1,alchimista:1}, school:'Evocazione', subschool:'', descriptor:'Fuoco', components:'V, S', castingTime:'1 azione standard', range:'Cono 4,5 m', target:'Creature nel cono', duration:'Istantanea', savingThrow:'Riflessi dimezza', spellResistance:'si', description:'1d4/livello danni fuoco (max 5d4) in cono 4,5 m.' },
  { name:'Incutere Paura',           level:{mago:1,stregone:1,arcanista:1,chierico:1,bardo:1,inquisitore:1}, school:'Necromanza', subschool:'', descriptor:'Paura, Mente', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Corta', target:'1 creatura vivente con 5 o meno DV', duration:'1d4 round', savingThrow:'Volontà parziale', spellResistance:'si', description:'Il bersaglio è in preda al terrore (fugge) per 1d4 round; successo al TS = scosso 1 round.' },
  { name:'Armatura del Mago',        level:{mago:1,stregone:1,arcanista:1}, school:'Congiunzione', subschool:'Creazione,Forza', descriptor:'Forza', components:'V, S, F', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 ora/livello (dis.)', savingThrow:'Volontà annulla (innocuo)', spellResistance:'no', description:'+4 armatura alla CA (bonus di armatura); non richiede indossare armatura fisica.' },
  { name:'Sopportare gli Elementi',  level:{mago:1,stregone:1,arcanista:1,chierico:1,druido:1,paladino:1,ranger:1,alchimista:1}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'24 ore', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Il soggetto sopporta temperature da -50°C a +60°C senza danno (non protegge da attacchi di fuoco/freddo).' },
  { name:'Ingrandire le Persone',    level:{mago:1,stregone:1,arcanista:1,alchimista:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 round', range:'Corta', target:'1 umanoide', duration:'1 minuto/livello (dis.)', savingThrow:'Volontà annulla', spellResistance:'si', description:'+2 FOR, -2 DES, -1 ai TxC, -1 CA, taglia aumenta di una categoria. Danni corpo a corpo aumentano.' },
  { name:'Ritirata Rapida',          level:{mago:1,stregone:1,arcanista:1,bardo:1,ranger:1,alchimista:1,inquisitore:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione libera', range:'Personale', target:'Incantatore', duration:'1 round/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'+9 m alla velocità base (solo a piedi) per la durata.' },
  { name:'Unto',                     level:{mago:1,stregone:1,arcanista:1,alchimista:1}, school:'Congiunzione', subschool:'Creazione', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Corta', target:'1 oggetto o creatura; o area 3 m x 3 m', duration:'1 round/livello (dis.)', savingThrow:'Riflessi annulla', spellResistance:'no', description:'Area scivolosa: creatura che ci entra deve superare Riflessi o cadere prona; +10 alle prove Agilità per sfuggire.' },
  { name:'Bloccare il Passaggio',    level:{mago:1,stregone:1,arcanista:1}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, F', castingTime:'1 azione standard', range:'Media', target:'1 porta, finestra o portello', duration:'1 ora/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Sbarra magicamente una porta (Forza per sfondare CD 23+livello; Aprire Serrature fallisce).' },
  { name:'Ipnotismo',                level:{mago:1,stregone:1,arcanista:1,bardo:1}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'Creature in raggio 7,5 m con max 2d4 DV', duration:'2d4 round (dis.)', savingThrow:'Volontà annulla', spellResistance:'si', description:'Ipnotizza creature deboli: seguono un\'azione semplice per la durata.' },
  { name:'Identificare',             level:{mago:1,stregone:1,arcanista:1,bardo:1,alchimista:1}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 minuto', range:'Tocco', target:'1 oggetto magico', duration:'Istantanea', savingThrow:'Volontà annulla (inanimato)', spellResistance:'no', description:'Rivela le proprietà magiche di un oggetto (come Individuare Magia + 10 minuti di Studio).' },
  { name:'Nebbia Oscurante',         level:{mago:1,stregone:1,arcanista:1,chierico:1,druido:1,ranger:1,alchimista:1}, school:'Congiunzione', subschool:'Creazione', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'Sfera di nebbia 6 m raggio', duration:'1 minuto/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Nebbia intensa ostruisce la vista: oscuramento totale (50% fallimento incantesimi).' },
  { name:'Protezione dal Male',      level:{mago:1,stregone:1,arcanista:1,chierico:1,paladino:1,inquisitore:1,bardo:2}, school:'Abiurazione', subschool:'', descriptor:'Bene', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 minuto/livello (dis.)', savingThrow:'Volontà annulla (innocuo)', spellResistance:'no', description:'+2 deflection alla CA e +2 ai TS contro creature del male; blocca la possessione da creature del male.' },
  { name:'Raggio di Debolezza',      level:{mago:1,stregone:1,arcanista:1}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Corta', target:'1 creatura', duration:'1 round/livello', savingThrow:'Nessuno', spellResistance:'si', description:'Raggio da tocco a distanza: 1d6 degradazione alla Forza +1/2 livelli (max 5d6); non riduce sotto 1 FOR.' },
  { name:'Rimpicciolire le Persone', level:{mago:1,stregone:1,arcanista:1,alchimista:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 round', range:'Corta', target:'1 umanoide', duration:'1 minuto/livello (dis.)', savingThrow:'Volontà annulla', spellResistance:'si', description:'-2 FOR, +2 DES, +1 ai TxC, +1 CA, taglia diminuisce di una categoria. Danni corpo a corpo diminuiscono.' },
  { name:'Immagine Silenziosa',      level:{mago:1,stregone:1,arcanista:1,bardo:1}, school:'Illusione', subschool:'Figura', descriptor:'', components:'V, S, F', castingTime:'1 azione standard', range:'Lunga (120 m + 12 m/livello)', target:'Immagine max 1,5 m c/livello', duration:'Concentrazione', savingThrow:'Indagare annulla', spellResistance:'no', description:'Crea immagine visiva silenziosa che puoi muovere entro il raggio.' },
  { name:'Colpo Vero',               level:{mago:1,stregone:1,arcanista:1,inquisitore:1,magus:1}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'Fino al tiro successivo o 1 round', savingThrow:'Nessuno', spellResistance:'no', description:'+20 al prossimo singolo tiro per colpire (non si accumula con altri bonus di insight).' },
  { name:'Servo Invisibile',         level:{mago:1,stregone:1,arcanista:1,bardo:1}, school:'Congiunzione', subschool:'Richiamo', descriptor:'', components:'V, S, M', castingTime:'1 round', range:'Corta', target:'1 servo invisibile', duration:'1 ora/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Crea una forza invisibile che esegue compiti semplici (porta oggetti, apre porte, max 20 kg).' },
  { name:'Saltare',                  level:{mago:1,stregone:1,arcanista:1,druido:1,ranger:1,alchimista:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, M', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 minuto/livello (dis.)', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'+10 competenza a Acrobazia per saltare (non il volo, solo il salto).' },
  { name:'Cavalcatura',              level:{mago:1,stregone:1,arcanista:1}, school:'Congiunzione', subschool:'Richiamo', descriptor:'', components:'V, S, M', castingTime:'1 round', range:'Corta', target:'1 cavalcatura evocata', duration:'2 ore/livello (dis.)', savingThrow:'Nessuno', spellResistance:'no', description:'Evoca un cavallo pesante docile (o altra bestia di taglia G) come cavalcatura.' },
  { name:'Tocco Gelido',             level:{mago:1,stregone:1,arcanista:1}, school:'Necromanza', subschool:'', descriptor:'Freddo', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creature toccate (1/livello)', duration:'Istantanea', savingThrow:'Fortitudine parziale', spellResistance:'si', description:'1d6/livello danni freddo (max 5d6) con attacco da tocco; creature viventi -1 FOR (TS annulla); nonmorti rimangono paralizzati 1d4 round.' },
  { name:'Disfavore',                level:{chierico:1,inquisitore:1}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S, DF', castingTime:'1 azione standard', range:'Corta', target:'Creature in raggio 15 m', duration:'1 minuto/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'-1 ai TxC e TS di paura a tutti i nemici nel raggio (opposto di Benedizione).' },
  { name:'Benedizione',              level:{chierico:1,paladino:1,inquisitore:1}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S, DF', castingTime:'1 azione standard', range:'Corta', target:'Alleati in raggio 15 m', duration:'1 minuto/livello', savingThrow:'Nessuno', spellResistance:'si', description:'+1 morale ai TxC e TS contro paura a tutti gli alleati nel raggio.' },
  { name:'Comando',                  level:{chierico:1,inquisitore:1}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Linguaggio, Mente', components:'V', castingTime:'1 azione standard', range:'Corta', target:'1 creatura vivente', duration:'1 round', savingThrow:'Volontà annulla', spellResistance:'si', description:'Il bersaglio segue un comando di una parola (avanzare, capitolare, fuggire, fermare, cadere).' },
  { name:'Condanna',                 level:{chierico:1,inquisitore:1}, school:'Necromanza', subschool:'', descriptor:'Paura, Mente', components:'V, S, DF', castingTime:'1 azione standard', range:'Corta', target:'1 creatura vivente', duration:'1 minuto/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'-2 ai TxC, ai tiri per danno e ai TS per 1 minuto.' },
  { name:'Favore Divino',            level:{chierico:1,paladino:1,inquisitore:1}, school:'Evocazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1 minuto', savingThrow:'Nessuno', spellResistance:'no', description:'+1 sacralità ai TxC e ai danni (+1 ogni 3 livelli; max +3) per 1 minuto.' },
  { name:'Infliggere Ferite Leggere',level:{chierico:1,inquisitore:1}, school:'Necromanza', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'Istantanea', savingThrow:'Volontà dimezza', spellResistance:'si', description:'Infligge 1d8+1/livello danni (max +5) a creature viventi; cura nonmorti dello stesso ammontare.' },
  { name:'Rimuovere la Paura',       level:{chierico:1,paladino:1,bardo:1,inquisitore:1}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'1 creatura/4 livelli in raggio 9 m', duration:'10 minuti', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'+4 morale ai TS paura per 10 minuti; sopprime l\'effetto paura attivo per 1 round.' },
  { name:'Santuario',                level:{chierico:1,inquisitore:1}, school:'Abiurazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 round/livello', savingThrow:'Volontà annulla (vedi testo)', spellResistance:'no', description:'I nemici non possono attaccare il soggetto (TS o cercano altro bersaglio); si annulla se il soggetto attacca.' },
  { name:'Individuare i Nonmorti',   level:{chierico:1,paladino:1,mago:1,stregone:1,arcanista:1,inquisitore:1}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S, M/DF', castingTime:'1 azione standard', range:'Cono 18 m', target:'Cone', duration:'Concentrazione, max 1 min/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Rivela la presenza e intensità delle aure di nonmorto nel cono; 1 round = presenza, 2 round = numero, 3 round = forza.' },
  { name:'Arma Magica',              level:{chierico:1,paladino:1,ranger:1,mago:1,stregone:1,arcanista:1,magus:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Tocco', target:'Arma toccata', duration:'1 minuto/livello', savingThrow:'Volontà annulla (inanimato)', spellResistance:'no', description:'+1 potenziamento all\'arma bersaglio (benedetta per scopi di resistenza); non si accumula con potenziamenti preesistenti.' },
  { name:'Intralciare',              level:{druido:1,ranger:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Lunga (120 m + 12 m/livello)', target:'Piante in raggio 9 m', duration:'1 minuto/livello (dis.)', savingThrow:'Riflessi parziale', spellResistance:'no', description:'Piante e rovi intralciano il movimento (terreno difficile). Chi fallisce il TS rimane intralciato.' },
  { name:'Fuoco delle Fate',         level:{druido:1}, school:'Evocazione', subschool:'', descriptor:'Luce', components:'V, S, DF', castingTime:'1 azione standard', range:'Lunga (120 m + 12 m/livello)', target:'Oggetti e creature in raggio 1,5 m', duration:'1 minuto/livello (dis.)', savingThrow:'Nessuno', spellResistance:'si', description:'Contorna le creature bersaglio di luce argentea/viola: non possono beneficiare di invisibilità; -20 alle prove Furtività.' },
  { name:'Bacche Salutari',          level:{druido:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Tocco', target:'2d6+1 bacche', duration:'1 giorno/livello', savingThrow:'Nessuno', spellResistance:'si', description:'Trasforma le bacche in cibo curativo: mangiarne una è come 1 giorno di cibo + può curare 1 PF.' },
  { name:'Passo Lungo',              level:{druido:1,ranger:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Tocco', target:'Creatura toccata', duration:'1 ora/livello (dis.)', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'+3 m alla velocità base di terra della creatura.' },
  { name:'Camminare senza Tracce',   level:{druido:1,ranger:1}, school:'Trasmutazione', subschool:'', descriptor:'', components:'V, S, DF', castingTime:'1 azione standard', range:'Tocco', target:'1 creatura/livello toccata', duration:'1 ora/livello', savingThrow:'Volontà annulla (innocuo)', spellResistance:'si', description:'Nessuna traccia fisica o olfattiva nel suo passaggio; Sopravvivenza per seguire le tracce fallisce.' },
  { name:'Produrre Fiamma',          level:{druido:1}, school:'Evocazione', subschool:'', descriptor:'Fuoco', components:'V, S', castingTime:'1 azione standard', range:'0 m', target:'Fiamma nella mano', duration:'1 minuto/livello (dis.)', savingThrow:'Nessuno', spellResistance:'si', description:'Crea una fiamma di 2,5 cm nella mano: illumina come torcia; puoi lanciarla come attacco a distanza (1d6+1/livello max 5d6 danni fuoco, gittata 9 m).' },
  { name:'Parlare con gli Animali',  level:{druido:1,ranger:1,bardo:2}, school:'Divinazione', subschool:'', descriptor:'', components:'V, S', castingTime:'1 azione standard', range:'Personale', target:'Incantatore', duration:'1 minuto/livello', savingThrow:'Nessuno', spellResistance:'no', description:'Comprendi e parli con gli animali normali (non bestie magiche); gli animali ostili potrebbero non cooperare.' },
  { name:'Calmare gli Animali',      level:{druido:1,ranger:1}, school:'Ammaliamento', subschool:'Compulsione', descriptor:'Mente', components:'V, S', castingTime:'1 azione standard', range:'Corta', target:'Animali in raggio 9 m con max 2d4+livello DV', duration:'1 minuto/livello', savingThrow:'Volontà annulla', spellResistance:'si', description:'Calma animali naturali (non bestie magiche): diventano amichevoli e non attaccano.' },
  { name:'Scudo Arcano',             level:{mago:1,stregone:1,arcanista:1,magus:1}, school:'Abiurazione', subschool:'', descriptor:'Forza', components:'V, S, M', castingTime:'1 azione immediata', range:'Personale', target:'Incantatore', duration:'1 round', savingThrow:'Nessuno', spellResistance:'no', description:'+4 scudo alla CA per 1 round (reazione immediata, blocca incluso Dardo Magico).' },

];"""

with open(path, 'w') as f:
    f.write(content + ',\n' + new_block)

import re
names = re.findall(r"name:'([^']+)'", open(path).read())
print(f"Done! Total spells now: {len(names)}")
